config/routes.rb
Greeting::Application.routes.draw do

    match '/admin', :to => 'admin#index'
    scope :path => '/admin', :controller => :admin do
        get  'index'
        get  'upload'
        post 'upload_template'
        get  'tag'
        post 'tag_a_card'
        post 'tag_card_from_image'
    end

    scope :path => '/users', :controller => :users do
        get  'index'   
        get  'send_card'  # This needs to be before the resources :users line below 
        get  'sign_card'   
        get  'sign_card_from_email'   
        get  'see_received'   
        get  'see_sent'   
        get  'see_signed'   
        get  'see_need_to_sign'   
        post 'do_sign'   
    end
    resources :users

    match '/all_cards', :to => 'cards#show_all_cards'
    scope :path => '/cards', :controller => :cards do
        get  'show_all_cards'
        get  'show_single_card'
        get  'show_card_from_email'
        post 'create_a_card'
        post 'create_from_image'   
        post 'from_preview'   
        get  'search'   
    end
    resources :cards, :only => [:create]

    resources :sessions, :only => [:new, :create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

    root :to => 'pages#home'
    match '/contact', :to => 'pages#contact'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'

    get "pages/home"
    get "pages/contact"
    get "pages/about"
    get "pages/help"

end

app/views/pages/about.html.haml
%h1 About
%p 
  GreetingSocial is a project by Scott LaBounty. If you'd like to work with him please feel free to use the 
  = link_to "Contact page", contact_path 
  to get in touch.

app/views/pages/contact.html.haml
%h1 Contact
Email: 
= mail_to "slabounty@gmail.com"
%br
Blog: 
= link_to "Steamcode", "http://www.steamcode.blogspot.com"
%br
LinkedIn: 
= link_to "Scott LaBounty", "http://www.linkedin.com/in/slabounty"

app/views/pages/help.html.haml
%h1 Help
%p Welcome to GreetingSocial! To get started Go to the Users page, pick someone, and send them a card! You can have your friends sign the card too. Simply add their email addresses in the box.

app/views/pages/home.html.haml
%h1 Greeting Social Application
%p This is the home page for the Greeting Social app.

-if !signed_in?
  = link_to "Sign up now!", signup_path, :class => "signup_button round"
= link_to "Check out our cards!", '/cards/show_all_cards', :class => "signup_button round"