config/routes.rb
Greeting::Application.routes.draw do

    match '/admin', :to => 'admin#index'
    scope :path => '/admin', :controller => :admin do
        get  'index'
        get  'upload'
        post 'upload_template'
        get  'tag'
        post 'tag_a_card'
        post 'tag_card_from_image'
    end

    scope :path => '/users', :controller => :users do
        get  'index'   
        get  'send_card'  # This needs to be before the resources :users line below 
        get  'sign_card'   
        get  'sign_card_from_email'   
        get  'see_received'   
        get  'see_sent'   
        get  'see_signed'   
        get  'see_need_to_sign'   
        post 'do_sign'   
    end
    resources :users

    match '/all_cards', :to => 'cards#show_all_cards'
    scope :path => '/cards', :controller => :cards do
        get  'show_all_cards'
        get  'show_single_card'
        get  'show_card_from_email'
        post 'create_a_card'
        post 'create_from_image'   
        post 'from_preview'   
        get  'search'   
    end
    resources :cards, :only => [:create]

    resources :sessions, :only => [:new, :create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

    root :to => 'pages#home'
    match '/contact', :to => 'pages#contact'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'

    get "pages/home"
    get "pages/contact"
    get "pages/about"
    get "pages/help"

end

app/views/layouts/_footer.html.erb
<footer>
    <nav class="round">
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%=  link_to logo, root_path %>
    <nav class="round">
        <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Cards", all_cards_path %></li>
            <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% end %>
            <% if admin? %>
                <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li><%= link_to "Help", help_path %></li>
            <% if signed_in? %>
                <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>

        <div id="searchBox">
            <%= form_tag ("/cards/search"), :method => :get do %>
                <%= text_field_tag(:search)%>
                <%= submit_tag("Search") %>
            <% end %>
        </div>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print' , :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %> <![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= title %></title>
        <%= csrf_meta_tags %>
        <%= render 'layouts/stylesheets' %>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag :application %>
    </head>
    <body>
        <div class="container">
            <%= render 'layouts/header' %>
            <section class="round">
                <% flash.each do |key, value| %>
                    <div class="flash <%= key %>"><%= value %></div>
                <% end %>
                <%= yield %>
            </section>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>